development:
  clients:
    default:
      uri: mongodb+srv://natan:saradao89@sinatraproj.139vl.mongodb.net/tcc?retryWrites=true&w=majority
      options:

test:
  clients:
    default: 
      uri: mongodb+srv://natan:saradao89@sinatraproj.139vl.mongodb.net/tcc_test?retryWrites=true&w=majority
      