# development:
#   clients:
#     default:
#       uri: <%= ENV["MONGO_URI_LOCAL"] %>
#       options:

development:
  clients:
    default:
      database: tcc_tinder
      hosts: 
        - <%= ENV["MONGO_URI_LOCAL"] %>